frase1 = ('Quem vem lá?')
frase2 =('Como te cumprimento?')
frase3 =('E se eu me apaixonar?')
frase4 =('Será para sempre amor ou só amizade?')
print(frase1, frase2, frase3, frase4)
nome = ('Qual o nome?')
endereço =('Qual o endereço?')
altura =('Qual a sua altura?')
print(nome, endereço, altura)
nome =('Qual o seu nome?')
idade =('Qual a sua idade?')
peso =('Qual o seu peso?')
print(nome, idade, peso)
